{
  "System.ProcessID": 9420,
  "Timestamp": "2025-02-03T07:27:08Z",
  "EventType": "CreateFile",
  "System": {
   "Channel": "NT Kernel Logger",
   "Computer": "WIN-SJE0CKQO83P",
   "EventType": "CreateFile",
   "EventID": {
    "Value": 0
   }
  },
  "EventData": {
   "IrpPtr": "0xFFFFD50BC2790C88",
   "FileObject": "0xFFFFD50BC5E093F0",
   "TTID": "9524",
   "CreateOptions": "18874368",
   "FileAttributes": "0",
   "ShareAccess": "7",
   "OpenPath": "C:\\WINDOWS\\SYSTEM32\\CONFIG\\SAM",
   "ProcInfo": {
    "Pid": 9420,
    "Ppid": 8072,
    "Name": "velociraptor.exe",
    "Threads": 51,
    "Username": "WIN-SJE0CKQO83P\\Administrator",
    "OwnerSid": "S-1-5-21-241402409-3571345782-2557608070-500",
    "CommandLine": "c:\\velociraptor.exe  gui --nobrowser --debug -v",
    "Exe": "C:\\velociraptor.exe",
    "TokenIsElevated": true,
    "CreateTime": "2025-02-02T06:44:31.5954257Z"
   }
  }
 }
