name: Check VQL in config

on:
  push:
    branches:
      - master  
  pull_request:

jobs:
  build:
    name: Windows Test
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v3
      
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '^1.20'

    - run: go version

    - name: Build Rules
      run: |
        make windows
        ./velosigmac.exe compile --config ./config/velociraptor_windows_rules.yaml --output ./output/rules.zip --yaml ./output/artifact.yaml

    - name: Download Velociraptor
      uses: robinraju/release-downloader@v1.8
      with:
        repository: velocidex/velociraptor
        latest: true
        fileName: "*-linux-amd64"
        out-file-path: "velociraptor"

    - run: 
        chmod +x velociraptor
        output/velociraptor.exe -v --definitions ./output/ query "SELECT * FROM Artifact.Windows.Sigma.CuratedRules(Debug=true)"