name: Check VQL in config

on: [pull_request]

jobs:
  build:
    name: Windows Rules Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '^1.20'
      id: go

    - name: Check out code
      uses: actions/checkout@v3

    - name: Download Velociraptor
      uses: robinraju/release-downloader@v1.8
      id: velociraptor
      with:
        repository: velocidex/velociraptor
        latest: true
        fileName: "*-linux-amd64"

    - name: Download evtx samples
      uses: actions/checkout@v2
      with:
        repository: sbousseaden/EVTX-ATTACK-SAMPLES
        path: ./samples/

    - name: Prepare events for scanning
      run: |
        mkdir /tmp/events
        mv ./samples/Execution/Exec_sysmon_meterpreter_reversetcp_msipackage.evtx /tmp/events/Microsoft-Windows-Sysmon%4Operational.evtx

    - name: Run Velociraptor
      run: |
        mv ${{ fromJson(steps.velociraptor.outputs.downloaded_files)[0]}} velociraptor
        chmod +x velociraptor
        make golden