name: Check VQL in config

on: [pull_request]

jobs:
  build:
    name: Windows Test
    runs-on: windows-2019
    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '^1.20'
      id: go

    - name: Check out code
      uses: actions/checkout@v3

    - name: Configure test environment
      shell: cmd
      if: always()
      run: |
        echo %PATH%
        echo %GOPATH%
        subst X: %CD%
        wevtutil.exe cl System
        sc.exe create TestingDetection1 binPath="%COMSPEC% /Q /c echo 'COMSPEC testing 1"

    - name: Build Rules
      run: |
        make windows
        ./velosigmac.exe compile --config ./config/velociraptor_windows_rules.yaml --output ./output/rules.zip --yaml ./output/artifact.yaml

    - name: Download Velociraptor
      uses: robinraju/release-downloader@v1.8
      id: velociraptor
      with:
        repository: velocidex/velociraptor
        latest: true
        fileName: "*-amd64.exe"

    - run: 
        ${{ fromJson(steps.velociraptor.outputs.downloaded_files)[0]}} -v --definitions ./output/ query "SELECT * FROM Artifact.Windows.Sigma.CuratedRules(Debug=true)"